INSERT INTO permissions VALUES('admin','bill',NULL,1);
INSERT INTO permissions VALUES('permission','bob',NULL,1);
INSERT INTO permissions VALUES('release','bob','{"products": ["fake", "a", "b"], "actions": ["create", "modify"]}',1);
INSERT INTO permissions VALUES('release','julie','{"products": ["a"], "actions": ["modify"]}',1);
INSERT INTO permissions VALUES('rule','julie','{"products": ["fake"], "actions": ["create"]}',1);
INSERT INTO permissions VALUES('release_read_only','bob','{"products": ["a", "b"], "actions": ["set"]}',1);
INSERT INTO permissions VALUES('rule','bob','{"products": ["a", "b"], "actions": ["modify"]}',1);
INSERT INTO permissions VALUES('release','ashanti','{"products": ["a"], "actions": ["modify"]}',1);
INSERT INTO permissions VALUES('scheduled_change','mary','{"actions": ["enact"]}',1);
INSERT INTO permissions VALUES('release_locale','ashanti','{"products": ["a"], "actions": ["modify"]}',1);
INSERT INTO permissions VALUES('admin','billy','{"products": ["a"]}',1);
INSERT INTO releases VALUES('a','a',1,'{"name": "a", "hashFunction": "sha512", "schema_version": 1}',0);
INSERT INTO releases VALUES('ab','a',1,'{"name": "ab", "hashFunction": "sha512", "schema_version": 1}',0);
INSERT INTO releases VALUES('b','b',1,'{"name": "b", "hashFunction": "sha512", "schema_version": 1}',0);
INSERT INTO releases VALUES('c','c',1,'{"name": "c", "hashFunction": "sha512", "schema_version": 1}',0);
INSERT INTO releases VALUES('d','d',1,'{"platforms": {"p": {"locales": {"d": {"complete": {"hashValue": "abc", "filesize": 1234, "from": "*"}}}}}, "name": "d", "hashFunction": "sha512", "schema_version": 1}',0);
INSERT INTO releases_history VALUES(1,'bill','ab',NULL,NULL,NULL,5,0);
INSERT INTO releases_history VALUES(2,'bill','ab','a',1,'{"name": "ab", "hashFunction": "sha512", "schema_version": 1}',6,0);
INSERT INTO releases_history VALUES(3,'bill','d',NULL,NULL,NULL,9,0);
INSERT INTO releases_history VALUES(4,'bill','d','d',1,'{"platforms": {"p": {"locales": {"d": {"complete": {"hashValue": "abc", "filesize": 1234, "from": "*"}}}}}, "name": "d", "hashFunction": "sha512", "schema_version": 1}',10,0);
INSERT INTO releases_history VALUES(5,'bill','b',NULL,NULL,NULL,15,0);
INSERT INTO releases_history VALUES(6,'bill','b','b',1,'{"name": "b", "hashFunction": "sha512", "schema_version": 1}',16,0);
INSERT INTO permissions_req_signoffs_history VALUES(1,'bill','doop','releng',NULL,NULL,10);
INSERT INTO permissions_req_signoffs_history VALUES(2,'bill','doop','releng',2,1,11);
INSERT INTO permissions_req_signoffs_history VALUES(3,'bill','doop','releng',1,2,25);
INSERT INTO product_req_signoffs_history VALUES(1,'bill','fake','k','relman',NULL,NULL,10);
INSERT INTO product_req_signoffs_history VALUES(2,'bill','fake','k','relman',2,1,11);
INSERT INTO product_req_signoffs_history VALUES(3,'bill','fake','k','relman',1,2,25);
INSERT INTO permissions_req_signoffs VALUES('fake','releng',1,1);
INSERT INTO permissions_req_signoffs VALUES('bar','releng',1,1);
INSERT INTO permissions_req_signoffs VALUES('blah','releng',1,1);
INSERT INTO permissions_req_signoffs VALUES('doop','releng',1,2);
INSERT INTO permissions_req_signoffs VALUES('superfake','relman',1,1);
INSERT INTO product_req_signoffs VALUES('fake','a','releng',1,1);
INSERT INTO product_req_signoffs VALUES('fake','e','releng',1,1);
INSERT INTO product_req_signoffs VALUES('fake','j','releng',1,1);
INSERT INTO product_req_signoffs VALUES('fake','k','relman',1,2);
INSERT INTO user_roles VALUES('bill','releng',1);
INSERT INTO user_roles VALUES('bill','qa',1);
INSERT INTO user_roles VALUES('bob','relman',1);
INSERT INTO user_roles VALUES('julie','releng',1);
INSERT INTO user_roles VALUES('mary','relman',1);
INSERT INTO rules VALUES(1,100,'c',100,'minor','a','3.5','a','d',NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO rules VALUES(2,100,'b',100,'minor','a','3.3','a','d',NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,'frodo',NULL,NULL,NULL,NULL,NULL);
INSERT INTO rules VALUES(3,100,'a',100,'minor','a','3.5','a','a',NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO rules VALUES(4,80,'a',100,'minor','fake',NULL,'a','d',NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO rules VALUES(5,80,'c',0,'minor','a','3.3','a','d',NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO rules VALUES(6,40,'a',50,'minor','fake',NULL,'e',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO rules VALUES(7,30,'a',85,'minor','fake',NULL,'c',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO rules VALUES(8,25,'a',100,'minor','fake2',NULL,'c',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,1,NULL);
INSERT INTO rules VALUES(9,25,'a',100,'minor','fake3',NULL,'c',NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,1);
