repos:
  schema: https://raw.githubusercontent.com/mozilla-releng/releng-dirschemas/master/repo.yaml
  projects:
    - /
pyup:
  schema: https://raw.githubusercontent.com/mozilla-releng/releng-dirschemas/master/pyup.yaml
  projects:
    - /
docker-compose:
  schema: https://raw.githubusercontent.com/mozilla-releng/releng-dirschemas/master/docker-compose.yaml
  projects:
    - /
apps:
  schema: https://raw.githubusercontent.com/mozilla-releng/releng-dirschemas/master/python-app.yaml
  projects:
    - /
tools:
  schema: https://raw.githubusercontent.com/mozilla-releng/releng-dirschemas/master/python-tool.yaml
  projects:
    - /agent
libs:
  schema: https://raw.githubusercontent.com/mozilla-releng/releng-dirschemas/master/python-lib.yaml
  projects:
    - /client
